# To set up Sonar cloud follow https://github.com/DEFRA/cdp-documentation/blob/main/howto/sonarcloud.md
# Update properties in this file as per the howto instructions
# Uncomment properties in this .github/workflows/check-pull-request.yml
# Uncomment properties in this .github/workflows/publish.yml
# Uncomment properties in this .github/workflows/publish-hotfix.yml

sonar.projectKey=DEFRA_mmo-cr-reference-data-service
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/mmo-cr-reference-data-service
sonar.links.ci=https://github.com/DEFRA/mmo-cr-reference-data-service/actions
sonar.links.scm=https://github.com/DEFRA/mmo-cr-reference-data-service
sonar.links.issue=https://github.com/DEFRA/mmo-cr-reference-data-service/issues

# Source code
sonar.sources=src
sonar.sourceEncoding=UTF-8
# Exclude test files completely from Sonar analysis
sonar.exclusions=**/*.test.js
# Test coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Exclude test files from coverage calculations
sonar.coverage.exclusions=**/*.test.js
# Exclude generated coverage output and dependencies
sonar.scm.exclusions.disabled=false