import { SERVICE_ERROR_CODES } from './errors.js'

export const HTTP_STATUS = Object.freeze({
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
})

// Both stale If-Match and duplicate collection-version conditions map to 409 in
// this repository (owner decision, 2026-09-16) — 412 is not used anywhere here.
const CODE_TO_STATUS = Object.freeze({
  [SERVICE_ERROR_CODES.INVALID_REQUEST]: HTTP_STATUS.BAD_REQUEST,
  [SERVICE_ERROR_CODES.INVALID_DATASET]: HTTP_STATUS.BAD_REQUEST,
  [SERVICE_ERROR_CODES.INVALID_JSON]: HTTP_STATUS.BAD_REQUEST,
  [SERVICE_ERROR_CODES.UNAUTHORIZED]: HTTP_STATUS.UNAUTHORIZED,
  [SERVICE_ERROR_CODES.FORBIDDEN]: HTTP_STATUS.FORBIDDEN,
  [SERVICE_ERROR_CODES.DATASET_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [SERVICE_ERROR_CODES.REFERENCE_ITEM_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [SERVICE_ERROR_CODES.MAP_LAYER_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [SERVICE_ERROR_CODES.COLLECTION_VERSION_EXISTS]: HTTP_STATUS.CONFLICT,
  [SERVICE_ERROR_CODES.COLLECTION_MODIFIED]: HTTP_STATUS.CONFLICT,
  [SERVICE_ERROR_CODES.DUPLICATE_IDENTIFIER]: HTTP_STATUS.CONFLICT,
  [SERVICE_ERROR_CODES.DUPLICATE_BUSINESS_CODE]: HTTP_STATUS.CONFLICT,
  [SERVICE_ERROR_CODES.FILE_TOO_LARGE]: HTTP_STATUS.PAYLOAD_TOO_LARGE,
  [SERVICE_ERROR_CODES.UNSUPPORTED_MEDIA_TYPE]:
    HTTP_STATUS.UNSUPPORTED_MEDIA_TYPE,
  [SERVICE_ERROR_CODES.SCHEMA_VALIDATION_FAILED]:
    HTTP_STATUS.UNPROCESSABLE_ENTITY,
  [SERVICE_ERROR_CODES.BUSINESS_VALIDATION_FAILED]:
    HTTP_STATUS.UNPROCESSABLE_ENTITY,
  [SERVICE_ERROR_CODES.AUTHENTICATION_SERVICE_UNAVAILABLE]:
    HTTP_STATUS.SERVICE_UNAVAILABLE,
  [SERVICE_ERROR_CODES.REFERENCE_STORE_UNAVAILABLE]:
    HTTP_STATUS.SERVICE_UNAVAILABLE,
  [SERVICE_ERROR_CODES.REFERENCE_DATA_UNAVAILABLE]:
    HTTP_STATUS.SERVICE_UNAVAILABLE,
  [SERVICE_ERROR_CODES.INTERNAL_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR
})

export function getHttpStatusForErrorCode(code) {
  return CODE_TO_STATUS[code] ?? HTTP_STATUS.INTERNAL_SERVER_ERROR
}
