// Stable, machine-readable validation issue codes shared by every validation stage.
export const VALIDATION_ISSUE_CODE = Object.freeze({
  INVALID_DOCUMENT: 'invalid_document',
  INVALID_ROOT_TYPE: 'invalid_root_type',
  REQUIRED_PROPERTY_MISSING: 'required_property_missing',
  INVALID_PROPERTY_TYPE: 'invalid_property_type',
  UNSUPPORTED_DATASET: 'unsupported_dataset',
  DATASET_MISMATCH: 'dataset_mismatch',
  INVALID_GUID: 'invalid_guid',
  DUPLICATE_GUID: 'duplicate_guid',
  UNSUPPORTED_SCHEMA_VERSION: 'unsupported_schema_version',
  INVALID_COLLECTION_VERSION: 'invalid_collection_version',
  INVALID_DATE: 'invalid_date',
  INVALID_DATE_RANGE: 'invalid_date_range',
  INVALID_ITEM_COUNT: 'invalid_item_count',
  DUPLICATE_BUSINESS_CODE: 'duplicate_business_code',
  UNRESOLVED_REFERENCE: 'unresolved_reference',
  INVALID_ENUM_VALUE: 'invalid_enum_value',
  UNEXPECTED_PROPERTY: 'unexpected_property',
  INVALID_GEOJSON_STRUCTURE: 'invalid_geojson_structure',
  BUSINESS_RULE_FAILED: 'business_rule_failed',
  VALIDATION_ISSUES_TRUNCATED: 'validation_issues_truncated',
  INVALID_COORDINATE: 'invalid_coordinate',
  OPEN_POLYGON_RING: 'open_polygon_ring',
  EMPTY_GEOMETRY: 'empty_geometry',
  MISSING_NATURAL_IDENTIFIER: 'missing_natural_identifier',
  UNSUPPORTED_CHARACTERISTIC_TYPE: 'unsupported_characteristic_type',
  INVALID_NUMERIC_RANGE: 'invalid_numeric_range',
  MISSING_APPLICABILITY: 'missing_applicability',
  DUPLICATE_OFFICIAL_NAME: 'duplicate_official_name'
})
